[package]
name = "websocket-chat-app"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.24.0"
axum = "0.6.20"
shuttle-axum = "0.24.0"
tokio = "1.32.0"
